<a href="https://colab.research.google.com/github/tejasbhosalepw/Assignments_by_tejas/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. What is a Python library? Why do we use Python libraries?

**Python Library** :- A Python library is a collection of pre-written code and functionalities that extend the capabilities of Python.
These libraries provide ready-to-use modules, functions, and classes that developers can import into their Python programs to perform specific tasks without having to write the code from scratch.

**Use of Python Libraries** :-
1.Code reusability.
2. Improves efficiency.
3. Specialized functionality.

Q2. What is the difference between Numpy array and List?

1. The Numpy array is faster than list because it stores homogoneus data.
2. The  Numpy array is faster than list because it takes less space to store data.
3.NumPy arrays are highly optimized for numerical computations and memory efficiency as compare to list.

Q3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
size = arr1.size
size

12

In [18]:
shape = arr1.shape
shape

(3, 4)

In [20]:
dimension  = arr1.ndim
dimension

2

Q4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [22]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
first_row = arr[0]
first_row

array([1, 2, 3, 4])

Q5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [23]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
elemnt = arr[2][3]
elemnt

12

Q6. Write co^e to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [27]:

import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
odd_indexed_elements = arr[:, 1::2]
odd_indexed_elements


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

Q7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [45]:
import random
arr = np.random.rand(3,3)
arr

array([[0.22826734, 0.79936439, 0.17180683],
       [0.14525635, 0.31193872, 0.34708345],
       [0.60192127, 0.15418245, 0.92825534]])

Q8. Describe the difference between np.random.rand and np.random.randn?

**np.random.rand**

1. Generates random numbers from a uniform distribution between 0 and 1.

2. All values generated are equally likely within the range [0, 1].

3. The shape of the output array is determined by the arguments passed to the function.

**np.random.randn**

1. Generates random numbers from a standard normal distribution (mean=0, standard deviation=1)

2. Random values are more likely to be closer to 0, with the probability decreasing as values move further away from 0 in both positive and negative directions.

3. The shape of the output array is determined by the arguments passed to the function.

Q9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [54]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
arr1 = arr.reshape(1,3,4)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

Q10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [62]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
arr1 = np.transpose(arr)
arr1

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Q11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
,+ Index wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om
+ Diide Matix B by A

In [63]:
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
# addition
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [66]:
# substraction
arr1 -arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
# multiplication
arr1 * arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [68]:
# division
arr1 / arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Q12. Which function in Numpy can be used to swap the byte order of an array?

**'byteswap'** method is used to swap the byte order of an array. This method is particularly useful when dealing with data that requires byte order conversion, suchas when reading binary data from different systems with different endian formats.

Q13. What is the significance of the np.linalg.inv function?

1. Inverse of a matrix
2. Solving Linear systems
3. Numerical Stability.
4. Error Handling

Q14. What does the np.reshape function do, and how is it used?

**np.reshape** :- It changes the shape of an array while preventing its data.
The total number of elements in the reshaped array must remain the same as the original array.

syntax:
np.reshape(arr, newshape, order='C')

In [69]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
reshape= np.reshape(arr, (3,2))
reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

Q15. What is broadcasting in Numpy?

**Broadcasting** in Numpy refers to a set of rules that allow arrays with different shapes to be combined together.

**Broadcasting works**:
1. When arrays have compatible dimensions.
2. Numpy automatically aligns the dimensions of arrays during broadcasting.
3. Broadcasting allows for efficient memory usage and computation.