<a href="https://colab.research.google.com/github/tejasbhosalepw/Assignments_by_tejas/blob/main/Python_control_flow_Assignment_3_9_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Write a Python program to check if a given number is positive or negative.

In [ ]:
num = int(input('enter the number'))
if num > 0:
  print('this is positive number')
elif num == 0:
  print('this is zero number')
else:
  print('this is negative number')

enter the number-1
this is negative number


Q2. Create a program that determines if a person is eligible to vote based on their age.

In [ ]:
age = int(input('enter the age'))
if age>=18:
  print('you are eligible for voting')
else:
  print('you are not eligible for voting')

enter the age18
you are eligible for voting


Q3. Develop a program to find the maximum of two numbers using if-else statements.

In [ ]:
number1 = int(input('enter the first number'))
number2 = int(input('enter the second number'))
if number1>number2:
  print(f'{number1} is maximum of {number1} & {number2}')
else:
  print(f"{number2} is maximum of {number1} & {number2}")

enter the first number12
enter the second number14
14 is maximum of 12 & 14


Q4. Write a Python script to classify a given year as a leap year or not.

In [ ]:
year = int(input('enter the year'))
if year%4 == 0:
  if year%100 != 0:
    print('this is leap year')
  else:
    print('not a leap year')
else:
  print('not a leap year')

enter the year2012
this is leap year


Q5. Create a program that checks whether a character is a vowel or a consonant.

In [ ]:
word = 'h'
vowel = ('aeiouAEIOU')
if word in vowel:
  print('this is vowel')
else:
  print('this is consonant')

this is consonant


Q6. Implement a program to determine whether a given number is even or odd.

In [ ]:
num = int(input('enter the number'))
if num%2 == 0:
  print('this is a even number')
else:
  print('this is odd number')

enter the number33
this is odd number


Q7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

In [ ]:
num = int(input('enter the number'))
print(abs(num))

enter the number-5
5


Q8. Develop a program that determines the largest of three given numbers using if-else statements.

In [ ]:
num1 = int(input('enter the first number'))
num2 = int(input('enter the second number'))
num3 = int(input('enter the third number'))
if num1>num2:
  if num1>num3:
    print(num1)
  else:
    print(num3)
elif num2>num3:
  print(num2)
else:
  print(num3)

enter the first number14
enter the second number12
enter the third number11
14


Q9. Create a program that checks if a given string is a palindrome.

In [ ]:
string = input('enter the string')
s1 = string[::-1]
if string==s1:
  print('this is palindrome string')
else:
  print('this is not a palindrome string')

enter the stringmom
this is palindrome string


Q10. Write a Python program to calculate the grade based on a student's score.

In [ ]:
s = int(input('enter your score'))
if s >70:
  print('distinction')
if s > 60:
  print('first class')
if s > 50:
  print('second class')
else:
  print('fail')

enter your score55
second class


Nested If-Else Statements:

Q11. Write a program to find the largest among three numbers using nested if-else statements.

In [ ]:
num1 = int(input('enter the first number'))
num2 = int(input('enter the second number'))
num3 = int(input('enter the third number'))
if num1>num2:
  if num1>num3:
    print(num1)
  else:
    print(num3)
elif num2>num3:
  print(num2)
else:
  print(num3)

enter the first number12
enter the second number4
enter the third number123
123


Q12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

In [ ]:
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))
if x == y == z:
	print("Equilateral triangle")
if x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")


Input lengths of the triangle sides: 
x: 12
y: 13
z: 12
isosceles triangle


Q13. Develop a program that checks if a year is a leap year and also if it is a century year.

In [ ]:
year = int(input('enter the year'))
if year%4 == 0:
  if year%100 != 0:
    print('this is leap year')
  else:
    print('not a leap year')
else:
  print('not a leap year')

enter the year2012
this is leap year


Q14. Write a Python script to determine if a number is positive, negative, or zero.

In [ ]:
num = int(input('enter the number'))
if num > 0:
  print('This is positive number')
if num == 0:
  print('zero number')
else:
  print('negative number')

enter the number-1
negative number


Q15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [ ]:
age = int(input('enter your age'))
if 19 > age > 13:
  print('person is teenager')
else:
  print('person is not a teenager')

enter your age22
person is not a teenager


Q16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

Q17. Write a Python program to calculate the roots of a quadratic equation.

In [ ]:
import cmath
a = float(input('Enter a: '))
b = float(input('Enter b: '))
c = float(input('Enter c: '))

d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print(f'The solution are {sol1} and {sol2}')

Enter a: 12
Enter b: 4
Enter c: 6
The solution are (-0.16666666666666666-0.6871842709362768j) and (-0.16666666666666666+0.6871842709362768j)


Q18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
for Tuesday, etc.).

In [ ]:
a = int(input('enter the number'))
if a ==1:
  print('Monday')
if a==2:
  print('Tuesday')
if a==3:
  print('Wednesday')
if a==4:
  print('Thursday')
if a==5:
  print('Friday')
if a==6:
  print('saturday')
if a==7:
  print('sunday')
else:
  print('enter number between 1 to 7')

enter the number1
Monday
enter number between 1 to 7


Q19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

In [ ]:
year = int(input('enter the year'))
if year%4 == 0:
  if year%100 == 0:
    if year%400 == 0:
      print('this is a leap year')
    else:
      print('not a leap year')
  else:
    print('leap year')

else:
  print('not a leap year')

enter the year3004
leap year


Q20. Develop a program that checks if a given number is prime or not using nested if-else statements.

In [ ]:
n = int(input('enter the number'))
prime = True
for i in range(2,n):
  if n%i == 0:
    prime = False
    break
if(prime==True):
  print('this is prime number')
else:
  print('this is not a prime number')

enter the number23
this is prime number


**Elif Statements**

Q21. Write a Python program to assign grades based on different ranges of scores using elif statements.

In [ ]:
n = int(input('enter the number'))
if n > 75:
  print('destination ')
elif n>60:
  print('first class')
elif n>50:
  print('second class')
else:
  print('fail')

enter the number55
second class


Q22. Implement a program to determine the type of a triangle based on its angles.

In [ ]:
a = int(input('enter the first angle'))
b = int(input('enter the second angle'))
c = int(input('enter the third angle'))
if a==b & b==c:
  print('This is equivalent trinagle')
elif a==b or b==c or a==c:
  print('This is isosceles triangle')
else:
  print('Scalene triangle')

enter the first angle60
enter the second angle60
enter the third angle60
This is equivalent trinagle


Q23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
elif statements.

In [ ]:
BMI = float(input('enter the your BMI'))
if BMI <= 18.5:
  print('you are underweight')
elif 18.5<BMI<24.5:
  print('your weight is normal')
elif BMI >= 24.5:
  print('you are overweight')
else:
  print('you are obese')

enter the your BMI19.5
your weight is normal


Q24. Create a program that determines whether a given number is positive, negative, or zero using elif
statements.

In [ ]:
num = int(input('enter the number'))
if num > 0:
  print(f'{num} is positive number')
elif num == 0:
  print(f'{num} is zero number')
else:
  print(f'{num} is negative number')

enter the number-1
-1 is negative number


Q25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
statements.

In [ ]:
string = input('enter the string: ')
if string.upper():
  print('uppercase')
elif string.lower():
  print('lowercase')
else:
  print('special')

enter the string: Hello
uppercase


Q26. Implement a program to calculate the discounted price based on different purchase amounts using elif
statements.

In [ ]:
purchase_amount = int(input('enter the purchase amount'))
if purchase_amount > 1000:
  print(f'your disocunted price is {purchase_amount*0.1}')
elif purchase_amount >500:
  print(f'your discounted price is {purchase_amount*0.05}')
else:
  print('you will not get any discount')

enter the purchase amount600
your discounted price is 30.0


Q27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
statements.

In [ ]:
unit = int(input('enter the units'))
if unit <=100:
  print(unit*10)
elif unit<=200:
  print(((100*10)+(unit-100)*15))
elif unit<=300:
  print(((100*10)+(100*15)+(unit-200)*15))
else:
  print('we can not calculate')

enter the units500
we can not calculate


Q28. Create a program to determine the type of quadrilateral based on its angles and sides using elif
statements.

Q29. Write a Python script to determine the season based on a user-provided month using elif statements.

In [ ]:
month = input('enter the month: ')
if month == 'may' or month =='feb' or month == 'march' or month == 'april':
    print('summer')
elif month == 'june' or month == 'july' or month == 'august' or month == 'september':
  print('Mansoon')
elif month == 'oct' or month=='nov' or month=='dec' or month=='jan':
  print('Winter')
else:
  print('zero')

enter the month: oct
Winter


Q30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
elif statements.

In [ ]:
year = int(input('enter the year'))
month = input('enter the month in word: ')
if (year%4) == 0:
  print('leap year')
else:
  print('common year')

if month == 'january' or month == 'march' or month== 'may' or month == 'july' or month == 'august' or month == 'octomber' or month == 'December':
  print('31 days month')
elif month == 'february':
  print('28 days month on common year and 29 days month on leap year')
else:
  print('30 days in month')

enter the year2000
enter the month in word: octomber
leap year
30 days in month


Basic Level:

Q1. Write a Python program that checks if a given number is positive, negative, or zero.

In [ ]:
num = int(input('enter the number'))
if num > 0:
  print(f'{num} is positive number')
elif num == 0:
  print(f'{num} is zero number')
else:
  print(f'{num} is negative number')

enter the number2
2 is positive number


Q2. Create a program to determine if a person is eligible to vote based on their age.

In [ ]:
Age = int(input('enter the age: '))
if Age >=18:
  print('you are eligible for voting')
else:
  print('you are not eligible for voting')

enter the age19
you are eligible for voting


Q3. Write a program to find the maximum of two given numbers using conditional statements.

In [ ]:
num1 = int(input('enter the first number'))
num2 = int(input('enter the second number'))
if num1 > num2:
  print(f'{num1} is greater than {num2}')
else:
  print(f'{num2} is greater than {num1}')

enter the first number12
enter the second number11
12 is greater than 11


Q4. Develop a program that calculates the grade of a student based on their exam score.

In [ ]:
score = int(input('enter your exam score: '))
if score >= 75:
  print('Distinction')
elif score >= 60:
  print('First class')
elif score >= 50:
  print('second class')
else:
  print('fail')

enter your exam score: 32
fail


Q5. Create a program that checks if a year is a leap year or not.

In [ ]:
year = int(input('enter the year: '))
if year%4 == 0:
  print(f'{year} is a leap year')
else:
  print(f'{year} is not a leap year ')

enter the year: 2020
2020 is a leap year


Q6. Write a program to classify a triangle based on its sides' lengths.

In [ ]:
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))
if x == y == z:
	print("Equilateral triangle")
if x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")


x: 70
y: 70
z: 40
isosceles triangle


Q7. Build a program that determines the largest of three given numbers.

In [ ]:
num1 = int(input('enter the first number'))
num2 = int(input('enter the second number'))
num3 = int(input('enter the third number'))
if num1>num2:
  if num1>num3:
    print(f'{num1} is largest among three numbers')
  else:
    print(f'{num3} is largest among three numbers')
elif num2>num3:
  print(f'{num2} is largest among three numbers')
else:
  print(f'{num3} is largest among three numbers')

enter the first number324
enter the second number324
enter the third number345
345 is largest among three numbers


Q8. Develop a program that checks whether a character is a vowel or a consonant.

In [ ]:
word = 'e'
vowel = ('aeiouAEIOU')
if word in vowel:
  print('this is vowel')
else:
  print('this is consonant')

this is vowel


Q9. Create a program to calculate the total cost of a shopping cart based on discounts.

In [ ]:
purchase_amount = int(input('enter the purchase amount'))
if purchase_amount > 1000:
  print(f'your disocunted price is {purchase_amount*0.1}')
elif purchase_amount >500:
  print(f'your discounted price is {purchase_amount*0.05}')
else:
  print('you will not get any discount')

enter the purchase amount32323
your disocunted price is 3232.3


Q10. Write a program that checks if a given number is even or odd.

In [ ]:
num = int(input('enter the number'))
if num%2==0:
  print(f'{num} is a even number')
else:
  print(f'{num} is a odd number')

enter the number3
3 is a odd number


**Intermediate Level**

Q11. Write a program that calculates the roots of a quadratic equation

In [ ]:
import cmath
a = float(input('Enter a: '))
b = float(input('Enter b: '))
c = float(input('Enter c: '))

d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print(f'The solution are {sol1} and {sol2}')

Enter a: 43
Enter b: 13
Enter c: 16
The solution are (-0.1511627906976744-0.5909677097475843j) and (-0.1511627906976744+0.5909677097475843j)


Q12. Create a program that determines the day of the week based on the day number (1-7).

In [ ]:
a = int(input('enter the number'))
if a ==1:
  print('Monday')
elif a==2:
  print('Tuesday')
elif a==3:
  print('Wednesday')
elif a==4:
  print('Thursday')
elif a==5:
  print('Friday')
elif a==6:
  print('saturday')
elif a==7:
  print('sunday')
else:
  print('enter number between 1 to 7')

enter the number5
Friday


Q13. Develop a program that calculates the factorial of a given number using recursion.

In [ ]:
num = int(input('enter the number'))
factorial = 1
for i in range(1, num+1):
  factorial = factorial * i
print(factorial)

enter the number5
120


Q14. Write a program to find the largest among three numbers without using the `max()` function.

In [ ]:
num1 = int(input('enter the first number'))
num2 = int(input('enter the second number'))
num3 = int(input('enter the third number'))
maximum_number = max(num1,num2,num3)
print(maximum_number)

54


Q15. Create a program that simulates a basic ATM transaction menu.

Q16. Build a program that checks if a given string is a palindrome or not.

In [ ]:
string = input('enter the word: ')
reverse_string = string[::-1]
if string == reverse_string:
  print('This is palindrome string')
else:
  print('this is not a palindrome string')

enter the word: mam
This is palindrome string


Q17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.

In [ ]:
from traitlets.config.configurable import MultipleInstanceError
list= [2,3,4,5,6,8]
list1 = []
max = 1
for i in list:
  if i > max:
    max = i
    # list.remove(max)
print(max)

min = 100
for i in list:
  if i<min:
    min = i
    # list.remove(min)
    # list1 -= i
list1 = list.remove(max)
print(min)
print(list1)

8
2
None


Q18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

In [ ]:
celsius = float(input('enter the temperature in celcius ')) # take input as floating num or integer num.
fahrenheit = (1.8 * celsius) + 32
print(f'Temperature of {celsius} celsius to Fahrenheit is {fahrenheit}')

enter the temperature in celcius 32.3
Temperature of 32.3 celsius to Fahrenheit is 90.13999999999999


Q19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

In [ ]:
# from traitlets.config.application import T
def Add(x,y):
  return x + y
def substract(x,y):
  return x - y
def multiply(x,y):
  return x * y
def divide(x,y):
  return x / y

print('select operation: ')
print('1.Add')
print('2.substract')
print('3.multiply')
print('4.divide')


choice = input('enter choice(1/2/3/4): ')

if choice in ('1','2', '3', '4'):
  num1 = float(input('enter first number: '))
  num2 = float(input('enter second number: '))

  if choice == '1':
    print(f'{num1} + {num2} = {Add(num1,num2)}')
  elif choice == '2':
    print(f'{num1} + {num2} = {substract(num1,num2)}')
  elif choice == '3':
    print(f'{num1} + {num2} = {multiply(num1, num2)}')
  elif choice == '4':
    print(f'{num1} + {num2} = {divide(num1,num2)}')
else:
  print('invalid input')

select operation: 
1.Add
2.substract
3.multiply
4.divide
enter choice(1/2/3/4): 1
enter first number: 21
enter second number: 32
21.0 + 32.0 = 53.0


Q20. Write a program that determines the roots of a cubic equation using the Cardano formula.

**Advanced Level**

Q21. Create a program that calculates the income tax based on the user's income and tax brackets.

In [ ]:
def calculate(amount, percent):
	return (amount * percent) / 100

def calculate_income_tax(total_income:
						float) -> float:

	if total_income <= 250000:
		return 0
	elif total_income <= 500000:
		return calculate(total_income -
						250000, 5)
	elif total_income <= 750000:
		return calculate(total_income -
						500000, 10) + 12500
	elif total_income <= 1000000:
		return calculate(total_income -
						750000, 15) + 37500
	elif total_income <= 1250000:
		return calculate(total_income -
						1000000, 20) + 75000
	elif total_income <= 1500000:
		return calculate(total_income -
						1250000, 25) + 125000
	else:
		return calculate(total_income -
						1500000, 30) + 187500


if __name__ == '__main__':
	total_income = float(input("What's your annual income?\n>>> "))
	tax = calculate_income_tax(total_income)
	print(f"Total tax applicable at \ ₹{total_income} is ₹{tax}")

What's your annual income?
>>> 359000
Total tax applicable at \ ₹359000.0 is ₹5450.0


Q22. Write a program that simulates a rock-paper-scissors game against the computer.

In [ ]:
import random
options = ["Rock", "Paper", "Scissors"]
user_choice = input("Choose Rock, Paper, or Scissors: ")
computer_choice = random.choice(options)
print("You chose: ", user_choice)
print("Computer chose: ", computer_choice)

if user_choice == computer_choice:
    print("It's a tie!")

elif user_choice == "Rock" and computer_choice == "Scissors":
    print("You win!")

elif user_choice == "Paper" and computer_choice == "Rock":
    print("You win!")

elif user_choice == "Scissors" and computer_choice == "Paper":
    print("You win!")
else:
    print("Computer wins!")

Choose Rock, Paper, or Scissors: Rock
You chose:  Rock
Computer chose:  Scissors
You win!


Q23. Develop a program that generates a random password based on user preferences (length, complexity).

In [ ]:
import random
import string
if __name__ == '__main__':
  s1 = string.ascii_lowercase
  s2 = string.ascii_uppercase
  s3 = string.digits
  s4 = string.punctuation

  plen = int(input('enter password length \n'))
  s = []
  s.extend(list(s1))
  s.extend(list(s2))
  s.extend(list(s3))
  s.extend(list(s4))
  print('your password is: ')
  # print(" ".join(random.sample(s,plen)))

enter password length 
9
your password is: "s" 


Q24. Create a program that implements a simple text-based adventure game with branching scenarios.

Q25. Build a program that solves a linear equation for x, considering different cases.

In [ ]:
def solve_linear(equation,var='x'):
    expression = equation.replace("=","-(")+")"
    grouped = eval(expression.replace(var,'1j'))
    return -grouped.real/grouped.imag
solve_linear("x - 2*x + 5*x - 46*(235-24) = x + 2")

3236.0

Q26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

In [ ]:
print("Wellcome to quiz game !!")
print('NOTE: if your spelling is incorrect then it is considered as wrong answer')
score = 0
question_no = 0
playing = input('Do you want to play ? ').lower()
if playing == 'yes':
    question_no += 1
    ques = input(f'\n{question_no}. what does CPU stand for? ').lower()
    if ques == 'central processing unit':
        score +=1
        print('correct! you got 1 point')
    else:
        print('Incorrect!')
        print(f'correct answer is --> central processing unit')

    question_no += 1
    ques = input(f'\n{question_no}. what does GPU stand for? ').lower()
    if ques == 'graphics processing unit':
        score +=1
        print('correct! you got 1 point')
    else:
        print('Incorrect!')
        print(f'correct answer is --> graphics processing unit')

    question_no += 1
    ques = input(f'\n{question_no}. what does RAM stand for? ').lower()
    if ques == 'random access memory':
        score +=1
        print('correct! you got 1 point')
    else:
        print('Incorrect!')
        print(f'correct answer is --> random access memory')
    question_no += 1
    ques = input(f'\n{question_no}. what does PSU stand for? ').lower()

    if ques == 'power supply unit':
        score +=1
        print('correct! you got 1 point')
    else:
        print('Incorrect!')
        print(f'correct answer is --> power supply unit')

    question_no += 1
    ques = input(f'\n{question_no}. what does ROM stand for? ').lower()

    if ques == 'read only memory':
        score +=1
        print('correct! you got 1 point')
    else:
        print('Incorrect!')
        print(f'current answer is --> read only memory')

else:
    print('thankyou you are out of a game.')
    quit()

print(f'\nnumber of question is {question_no}')
print(f'your score is {score}')
try:
    percentage = (score *100)/question_no
except ZeroDivisionError:
    print('0% quetions are correct')

print(f'{percentage}% questions are correct.')

Wellcome to quiz game !!
NOTE: if your spelling is incorrect then it is considered as wrong answer
Do you want to play ? no
thankyou you are out of a game.

number of question is 0
your score is 0
0% quetions are correct
20.0% questions are correct.


Q27. Develop a program that determines whether a given year is a prime number or not.

In [ ]:
num = int(input('enter the num'))
Prime = True
for i in range(2,num):
  if num%i ==0:
    Prime= False
    break
if Prime == True:
  print(f'{num} is a prime number')
else:
  print(f'{num} is not a prime number')

enter the num13
13 is a prime number


Q28. Create a program that sorts three numbers in ascending order using conditional statements.

In [ ]:
a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))

if a > b:
    a,b = b,a
if a > c:
    a,c = c,a
if b > c:
    b,c = c,b

print (a, "<", b, "<", c)

Enter a: 23
Enter b: 12
Enter c: 11
11.0 < 12.0 < 23.0


Q29. Build a program that determines the roots of a quartic equation using numerical methods.

In [ ]:
import cmath
a = float(input('Enter a: '))
b = float(input('Enter b: '))
c = float(input('Enter c: '))

d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print(f'The solution are {sol1} and {sol2}')

Enter a: 12
Enter b: 14
Enter c: 16
The solution are (-0.5833333333333334-0.9965217285917832j) and (-0.5833333333333334+0.9965217285917832j)


Q30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based
on the user's input.

In [ ]:
wt = int(input('enter your weight in kg: '))
height = float(input('enter the height in meter: '))
bmi = wt/(height*height)
print(bmi)
if bmi >= 20:
  print('you are healthy')
elif bmi >=10:
  print('you need some improvment')
else:
  print('you are too weak need lots of improvement')


enter your weight in kg: 60
enter the height in meter: 2.3
11.342155009451798
you need some improvment


**Challenge Level**

Q31. Create a program that validates a password based on complexity rules (length, characters, etc.).

In [ ]:
import string
import random
# from time import time
if __name__ == "__main__":
    # init = time()
    s1 = string.ascii_lowercase
    s2 = string.ascii_uppercase
    s3 = string.digits
    s4 = string.punctuation
    plen = int(input("enter password length\n"))
    s = []
    s.extend(list(s1))
    s.extend(list(s2))
    s.extend(list(s3))
    s.extend(list(s4))

    random.shuffle(s)
    print("".join(s[0:plen]))
    # print("time required to execute this is", time()-init)



enter password length
8
tl%D.@Jv


Q32. Develop a program that performs matrix addition and subtraction based on user input.

In [ ]:
import numpy as np

# creating first matrix
A = np.array([[1, 2,5], [3, 4,6]])
B = np.array([[4, 5,6], [6, 7,8]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))
print('substraction of two matrix')
print(np.subtract(A,B))

Printing elements of first matrix
[[1 2 5]
 [3 4 6]]
Printing elements of second matrix
[[4 5 6]
 [6 7 8]]
Addition of two matrix
[[ 5  7 11]
 [ 9 11 14]]
substraction of two matrix
[[-3 -3 -1]
 [-3 -3 -2]]


Q33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
algorithm.

In [ ]:
import math
print("The gcd of 60 and 48 is : ", end="")
print(math.gcd(60, 48))

The gcd of 60 and 48 is : 12


Q34. Build a program that performs matrix multiplication using nested loops and conditional statements.

In [ ]:
import numpy as np
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]

B = [[5, 8, 1],
	[6, 7, 3],
	[4, 5, 9]]

result=[[0,0,0],
		[0,0,0],
		[0,0,0]]

result = np.dot(A,B)

for r in result:
	print(r)


[114 160  60]
[74 97 73]
[119 157 112]


Q35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.

In [ ]:
import numpy as np
import random
from time import sleep
def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board
def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):
			if board[i][j] == 0:
				l.append((i, j))
	return(l)
def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)
def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue
		if win == True:
			return(win)
	return(win)

def col_win(board, player):
	for x in range(len(board)):
		win = True
		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue
		if win == True:
			return(win)
	return(win)

def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

def evaluate(board):
	winner = 0
	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)

# Driver Code
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[1 0 0]
 [0 0 0]
 [0 2 0]]
Board after 3 move
[[1 1 0]
 [0 0 0]
 [0 2 0]]
Board after 4 move
[[1 1 0]
 [0 0 0]
 [2 2 0]]
Board after 5 move
[[1 1 1]
 [0 0 0]
 [2 2 0]]
Winner is: 1


Q36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.

In [ ]:
a = 0
b = 1
n=int(input("Enter the number of terms in the sequence: "))
print(a,b,end=" ")
while(n-2):
    c=a+b
    a,b = b,c
    print(c,end=" ")
    n=n-1

Enter the number of terms in the sequence: 2
0 1 

Q37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.

In [ ]:
def Fibonacci(n):
	if n<= 0:
		print("Incorrect input")
	elif n == 1:
		return 0
	elif n == 2:
		return 1
	else:
		return Fibonacci(n-1)+Fibonacci(n-2)

print(Fibonacci(10))

34


Q38. Create a program that generates a calendar for a given month and year using conditional statements.

In [ ]:
import calendar
year = int(input ("Please enter the Year: "))
month = int(input ("Please enter the month: "))

print("The Calendar of: ", calendar.month(year, month))

Please enter the Year: 2023
Please enter the month: 9
The Calendar of:     September 2023
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



Q39. Build a program that simulates a basic text-based blackjack game against the computer.

In [ ]:
import random

card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King']
deck = [(card, category) for category in card_categories for card in cards_list]

def card_value(card):
	if card[0] in ['Jack', 'Queen', 'King']:
		return 10
	elif card[0] == 'Ace':
		return 11
	else:
		return int(card[0])

random.shuffle(deck)
player_card = [deck.pop(), deck.pop()]
dealer_card = [deck.pop(), deck.pop()]

while True:
	player_score = sum(card_value(card) for card in player_card)
	dealer_score = sum(card_value(card) for card in dealer_card)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("\n")
	choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower()
	if choice == "play":
		new_card = deck.pop()
		player_card.append(new_card)
	elif choice == "stop":
		break
	else:
		print("Invalid choice. Please try again.")
		continue

	if player_score > 21:
		print("Cards Dealer Has:", dealer_card)
		print("Score Of The Dealer:", dealer_score)
		print("Cards Player Has:", player_card)
		print("Score Of The Player:", player_score)
		print("Dealer wins (Player Loss Because Player Score is exceeding 21)")
		break

while dealer_score < 17:
	new_card = deck.pop()
	dealer_card.append(new_card)
	dealer_score += card_value(new_card)

print("Cards Dealer Has:", dealer_card)
print("Score Of The Dealer:", dealer_score)
print("\n")

if dealer_score > 21:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)")
elif player_score > dealer_score:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Player wins (Player Has High Score than Dealer)")
elif dealer_score > player_score:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Dealer wins (Dealer Has High Score than Player)")
else:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("It's a tie.")


Cards Player Has: [('2', 'Clubs'), ('3', 'Diamonds')]
Score Of The Player: 5


What do you want? ["play" to request another card, "stop" to stop]: play
Cards Player Has: [('2', 'Clubs'), ('3', 'Diamonds'), ('Queen', 'Spades')]
Score Of The Player: 15


What do you want? ["play" to request another card, "stop" to stop]: stop
Cards Dealer Has: [('6', 'Clubs'), ('8', 'Hearts'), ('Jack', 'Clubs')]
Score Of The Dealer: 24


Cards Dealer Has: [('6', 'Clubs'), ('8', 'Hearts'), ('Jack', 'Clubs')]
Score Of The Dealer: 24
Cards Player Has: [('2', 'Clubs'), ('3', 'Diamonds'), ('Queen', 'Spades')]
Score Of The Player: 15
Player wins (Dealer Loss Because Dealer Score is exceeding 21)


Q40. Write a program that generates the prime factors of a given number using trial division.

In [ ]:
import math
def prime_factors(num):
    while num % 2 == 0:
        print(2,)
        num = num / 2
    for i in range(3, int(math.sqrt(num)) + 1, 2):

        # while i divides n , print i ad divide n
        while num % i == 0:
            print(i,)
            num = num / i
    if num > 2:
        print(num)
num = 200
prime_factors(num)

2
2
2
5
5
